version: "3.7"

services:
  jm-vue-admin-template:
    container_name: jm-vue-admin-template
    image: "ijohnnymiller/jm-vue-admin-template-stage:${TAG}"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ENV: stage
        ENV_ALIAS: stage
    ports:
      - 8081:80
